name-template: 'v$RESOLVED_VERSION :rainbow:'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes
  $CHANGES

categories:
  - title: ':rocket: Features'
    labels:
      - 'feature'
  - title: 'Improvements'
    labels:
      - 'enhancement'
  - title: 'Tests'
    labels:
      - 'test'
  - title: ':bug: Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'hotfix'
      - 'revert'
  - title: ':toolbox: Maintenance'
    labels:
      - 'docs'
      - 'chore'
      - 'build'
      - 'ci'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'test'
      - 'hotfix'

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/refactor\/.+/'
      - '/perf\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
  - label: 'docs'
    files:
      - '*.md'
      - '*.txt'
      - '*.png'
    branch:
      - '/docs\/.+/'
  - label: 'test'
    branch:
      - '/test\/.+/'
  - label: 'ci'
    files:
      - '*.yml'
    branch:
      - '/ci\/.+/'
  - label: 'revert'
    title:
      - '/revert/i'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'