name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.release_drafter.outputs.tag_name }}

    steps:
      - id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-version:
    runs-on: ubuntu-latest

    needs: [update_release_draft]

    steps:
    - name: Check Publish label
      id: check-publish-label
      uses: shioyang/check-pr-labels-on-push-action@v1.0.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["publish"]'

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Bump Version
      if: ${{ steps.check-publish-label.outputs.result == 'true' }}
      run: ./bump-rockspec.sh ${{ needs.update_release_draft.outputs.tag_name }}
