name: Pull Request Target Test Workflow

on:
  pull_request_target

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      - run: echo "Pull request from forked branch"
      - run: echo ${{ secrets.LUAROCKS_KEY }}
